### PR TITLE
add nutshell figure

### LINKED ISSUE #26: Add new Figure 1

### PR DESCRIPTION
**Pull request by aaronpeikert**
nutshell
closes #26

### CODE REVIEW

**Comment by aaronpeikert** [comment]
Now ready for merge.

**Comment by brandmaier** [comment]
Very nice! Two things:
- the arrows for time (left-hand side across git versions) is the same as the dependency arrow. Let's make them distinct
- The dependency arrow is percetually very similar to the git version frames. Can we make them stand out a little more?

A solution to both problems would be to choose a different line type/color/width for the dependency arrows.

**Comment by brandmaier** [comment]
maybe long-dashes as line type for dependencies?

Otherwise, it's great.

**Comment by brandmaier** [comment]
one more thing: if we stay with renaming as suggested earlier, "clean.R" should become "process.R" and dependency should include "manuscript.Rmd".

**Comment by aaronpeikert** [comment]
> one more thing: if we stay with renaming as suggested earlier, "clean.R" should become "process.R" and dependency should include "manuscript.Rmd".

@cjvanlissa uses the name `prepare_data.R` 
I like process more (because it is more generic) but I am in a mental pat, you have to decide...

**Comment by aaronpeikert** [comment]
> Very nice! Two things:
> 
> * the arrows for time (left-hand side across git versions) is the same as the dependency arrow. Let's make them distinct
> * The dependency arrow is percetually very similar to the git version frames. Can we make them stand out a little more?
> 
> A solution to both problems would be to choose a different line type/color/width for the dependency arrows.

I overlooked the dashed line advice for make dependencies, now it looks like:
https://github.com/aaronpeikert/reproducible-research/tree/2f5632515619d850c503314ae4fce98362cc53e7

**Comment by cjvanlissa** [comment]
I think clean, process, and prepare are all fine - but for readability I'd add a noun, like "_data".

It's also important to consider that the clean_data file might not be the entry point to the project for secondary analyses, so I also add a run_me.R or simply the Rmd as primary entry point.

**Comment by aaronpeikert** [comment]
cross ref: aaronpeikert/repro#29

**Comment by aaronpeikert** [comment]
> I think clean, process, and prepare are all fine - but for readability I'd add a noun, like "_data".

I agree.
@brandmaier your call: `clean_data`, `preprocess_data` or `prepare_data`?

**Comment by brandmaier** [comment]
great work, @aaronpeikert! Let's stay as close as possible to worcs, so prepare_data it is.

**Review by brandmaier — APPROVED** [review]
Wow! I am really impressed that even inkscape is now in the container!

**Pull request merged**
